Fixes https://github.com/android/android-test/issues/1458
android/android-test pull request #1459
Opened 2022-08-04 00:50 UTC by yogurtearl

fixes #1458 

Rather than trying to guess the toolType from the source/inputDevice,
if we have an event that we are copying from, we can just copy toolType
directly.

When we are NOT copying an event, we just fallback to the existing logic.

2022-08-16 00:07 UTC, ralf-at-android requested changes
This looks good.
Please update matching unit test https://github.com/android/android-test/blob/master/espresso/core/javatests/androidx/test/espresso/action/MotionEventsUnitTest.java

2022-10-11 11:50 UTC, hrach commented
@yogurtearl would you have a bit of time please to proceed here? :) thx

2022-10-11 14:11 UTC, yogurtearl commented
I can't get the tests to run on my arm64 mac (inside a docker container).

I may be able to get them to run on my personal Intel mac, but need to create a docker image with all the right dependencies.

Do you have a Docker image or Dockerfile handy that can run the full test suite? 😅

2022-10-11 14:16 UTC, hrach commented
TBH I have no experience with Docker on Mac (new user here) nor with Java/Android testing in Docker.

2022-10-31 18:25 UTC, merged