Create script for cherry picking to release branch
android/android-test pull request #2234
Opened 2024-05-29 19:26 UTC by brettchabot

2024-05-30 05:14 UTC, AkshDesai04 approved these changes
Can't we already fire a git status instead of telling the user to do so?

2024-05-30 05:24 UTC, AkshDesai04 requested changes
Adding a call for git status ourselves would make it more functional.

`if [[ -n $(git status -s) ]]; then`
`    echo "Error: git directory is not clean; Running 'git status'"`
`    git status`
`    exit 1`
`fi`

2024-05-30 08:32 UTC, TWiStErRob commented on tools/release/cherrypick_to_release_branch.sh
> +    echo "Error: RELEASE_BRANCH env var is undefined or does not contain 'release_branch'"
output the value to show which one?
```suggestion
    echo "Error: RELEASE_BRANCH env var (${RELEASE_BRANCH}) is undefined or does not contain 'release_branch'"
```

2024-05-31 03:19 UTC, AkshDesai04 commented on tools/release/cherrypick_to_release_branch.sh
> +    echo "Error: git directory is not clean; check 'git status'"
```suggestion
    echo "Error: git directory is not clean; running 'git status'"
    git status
```

2024-06-26 19:58 UTC, merged